REM GUI Programs
choco install googlechrome -y
choco install winrar -y
choco install firefox -y
choco install 7zip.install -y
choco install steam -y
choco install skype -y
choco install visualstudiocode -y
choco install telegram -y
choco install ccleaner -y
choco install malwarebytes -y
choco install atom -y
choco install virtualbox -y
choco install dropbox -y
choco install teamviewer -y
choco install itunes -y
choco install gimp -y
choco install calibre -y
choco install unity -y
choco install cyberduck.install -y
choco install whatsapp -y
choco install slack -y
choco install f.lux -y
choco install postman -y
choco install robo3t.install -y
choco install etcher -y
choco install obs-studio -y
choco install arduino -y
choco install handbrake -y
choco install velocity -y
choco install google-backup-and-sync -y

REM CLI tools
choco install python3 -y
choco install youtube-dl -y
choco install git.install -y
choco install neovim -y
choco install curl -y
choco install wget -y
choco install mongodb -y
choco install nodejs.install -y